### ISSUE TITLE
Syntax Error when trying to deploy with Meteor Up

### ISSUE THREAD

**Issue by abeaudoin2013** [VeliovGroup/meteor-autoform-file#24]
Hey there, not sure if this is related #21, but I am having issues deploying to digital ocean using Meteor Up. (I'm using meteor version 1.4.3.2)

```
$ mup deploy
Building App Bundle Locally
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error: 

SyntaxError: Unexpected token: punc ()) at
packages/ostrio_autoform-files/lib/client/fileUpload.js line 16

within packages/ostrio_autoform-files.js (line: 195, col: 25, pos: 18455):

this.collectionName = () => {

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
at packages/minifyStdJS_plugin.js:145:9
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle
(packages/minifyStdJS_plugin.js:130:9)



=> Build Error. Check the logs printed above.
Error: build-error
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/mup/lib/modules/meteor/build.js:46:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I believe my mup.js file is set up correctly: 

```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '138.197.101.26',
      username: 'root',
      password: '*******'
    }
  },

  meteor: {
    // TODO: change app name and path
    name: 'AnnaLublina',
    path: '.',
    volumes: {
      '/images':'/images'
    },

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'http://138.197.101.26',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
      // imagePort: 80, // (default: 80, some images EXPOSE different ports)
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
````

And my collection setup: 

```
Images = new FilesCollection({
  collectionName: 'Images',
  storagePath: '../images',
  allowClientCode: true, // Required to let you remove uploaded file
  permissions: 0774,
	parentDirPermissions: 0774,
  onBeforeRemove: function (cursor) {
    if (this.userId) {
      var user = this.user();
      if (Roles.userIsInRole(user, 'admin')) {

        var imgId = cursor._selector;
        var project = Projects.findOne({pictures: {$in: [imgId]}});
        var p_id = project._id;
        Projects.update({"_id": p_id}, {"$pull": {"pictures": imgId}});
        return true;
        
      }
    }
    return false;
  }
});
```

Any ideas as to what may be going wrong?

**Comment by jlourenco** [comment]
Check [this](https://github.com/VeliovGroup/meteor-autoform-file/issues/23)

**Comment by dr-dimitru** [comment]
Hello @abeaudoin2013 ,

Is [this comment](https://github.com/VeliovGroup/meteor-autoform-file/issues/23#issuecomment-284379349) helped you, I saw your messages at meteor rep thread, - I assume switching to `abernix:standard-minifier-js` package not helped at all. Right?

Is error changed?

**Comment by dr-dimitru** [comment]
Hi @obiwarn ,

I saw your related messages at meteor rep thread, have you solved this?

**Comment by abeaudoin2013** [comment]
That commented helped, yes. Thank you! 

I'm getting different errors now though: 

```
	npm ERR! node v4.8.0
	npm ERR! npm  v3.10.10
	npm ERR! code ELIFECYCLE
	npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node npm-rebuild.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs meteor-dev-bundle
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls meteor-dev-bundle
	npm ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     /bundle/bundle/programs/server/npm-debug.log
	 
	=> Redeploying previous version of the app
```

**Comment by abeaudoin2013** [comment]
but it's unrelated to this thread, I suppose.

**Comment by dr-dimitru** [comment]
@abeaudoin2013 

NPM is outdated, run:
```shell
npm install -g npm@4
```

**Comment by abeaudoin2013** [comment]
That didn't seem to work, unfortunately.

**Comment by dr-dimitru** [comment]
What if you run `meteor reset` and make sure `.meteor/local` is gone?
__Warning: this will drop project's bundled mongo db__
Then `meteor npm install`
and `meteor run`

**Comment by abeaudoin2013** [comment]
Can confirm that it works locally. Testing deploy again...

**Comment by abeaudoin2013** [comment]
No npm-rebuild error, but looks like bcrypt or node-pre-gyp error...

```
	-----------------------------------STDERR-----------------------------------
	   at ChildProcess.<anonymous> (/bundle/bundle/programs/server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
	node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
	node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:854:16)
	node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
	node-pre-gyp ERR! System Linux 4.4.0-70-generic
	node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/bundle/bundle/programs/server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/bcrypt
	node-pre-gyp ERR! node -v v4.8.0
	node-pre-gyp ERR! node-pre-gyp -v v0.6.33
	node-pre-gyp ERR! not ok 
	
	npm ERR! Linux 4.4.0-70-generic
	npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
	npm ERR! node v4.8.0
	npm ERR! npm  v3.10.10
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------
```

**Comment by dr-dimitru** [comment]
Could you try to build app:
```shell
# Build an app ypourself
# Available architectures:
# os.osx.x86_64
# os.linux.x86_64
# os.linux.x86_32
# os.windows.x86_32
meteor build ../ --architecture os.linux.x86_64
```

Let's see if it will run into the same error

**Comment by abeaudoin2013** [comment]
Hmm... still looks like a bcrypt error after trying to deploy again...

```
	-----------------------------------STDERR-----------------------------------
	/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
	node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
	make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
	  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
	  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
	g++: internal compiler error: Killed (program cc1plus)
	Please submit a full bug report,
	with preprocessed source if appropriate.
	See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
	bcrypt_lib.target.mk:98: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
	make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
	make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 4
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------
```

**Comment by dr-dimitru** [comment]
Could you try to build app without involving MUP? See [this message](https://github.com/VeliovGroup/meteor-autoform-file/issues/24#issuecomment-290473755)

**Comment by abeaudoin2013** [comment]
Yeah, I ran the build command locally, and then tried to deploy. Did you mean something else?

**Comment by dr-dimitru** [comment]
I mean if it builds locally, then this issue relative only to MUP.
As when you do deploy via MUP it's builds app and doing its own "magic".

**Comment by obiwarn** [comment]
A downgrade to the last (pre ES6) version of the ostrio package helped in my case.

change packages file to:

`ostrio:autoform-files@=1.0.11`

**Comment by abeaudoin2013** [comment]
Thanks, I'll give that a try!

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
